all:
  vars:
    ansible_ssh_private_key_file: test.pem
    ansible_user: ec2-user
  hosts: #all ungrouped hosts

  children: #group of hosts
   webservers: # First group of hosts
     hosts:
       web1:
        ansible_host: 172.31.29.132
        ansible_user: ec2-user
        ansible_ssh_private_key_file: test.pem
       web2:
         ansible_host: 172.31.20.51
         ansible_user: ec2-user

   db: # Second group of hosts
     hosts:
       dbcentos:
         ansible_host: 172.31.17.208
         ansible_user: ec2-user