---
- name: Install Apache and MySQL for WordPress
  hosts: front
  become: true
  vars:
    wordpress_version: "6.0.2"  
    wordpress_install_directory: "/var/www/html"  
    wordpress_directory: "{{ wordpress_install_directory }}/wordpress"

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: restarted
        enabled: yes

- name: Install MySQL and WordPress Prerequisites
  hosts: front
  become: true
  vars_files:
    - vars/packs.yaml
    - vars/default.yaml

  tasks:
    - name: Install MariaDB on RedHat
      dnf:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      when: ansible_distribution == "RedHat"
      with_items: "{{ packs }}"

    - name: Start and Enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install PyMySQL for RedHat
      dnf:
        name: python3-PyMySQL.noarch 
        state: present
      when: ansible_distribution == "RedHat"

    - name: Install WordPress Prerequisites
      package:
        name: "{{ wordpress_packages }}"
        state: present
      tags: wordpress

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
        dest: "{{ wordpress_install_directory }}/wordpress-{{ wordpress_version }}.tar.gz"
      tags: wordpress

    - name: Unzipping WordPress
      unarchive:
        src: "{{ wordpress_install_directory }}/wordpress-{{ wordpress_version }}.tar.gz"
        dest: "{{ wordpress_install_directory }}"
        remote_src: true
        owner: apache
        group: apache
      tags: wordpress
