---
- name: Install Apache
  hosts: front
  become: true
  tasks:
    - name: Download and Install Apache
      yum: 
        name: httpd
        state: present
    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Download and Install Apache
      yum: 
        name: "{{ item }}"
        state: present
      loop:
       - wget
       - zip
       - unzip
       - git
- name: Install MySQL
  hosts: front
  vars_files:
    - vars/packs.yaml
  become: True
  tasks:
    - name: Install Mariadb on RedHat
      dnf:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      when: ansible_distribution == "RedHat"
      with_items: "{{ packs }}"

    - name: Start and Enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Install PyMysql RedHat
      dnf:
        name: python3-PyMySQL.noarch 
        state: present
      when: ansible_distribution == "RedHat"
    - name: Install Wordpress Prerequisites
      package:
        name: "{{ wordpress_packages }}"
        state: present
      tags: wordpress

    - name: Download Wordpress
      get_url:
        url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
        dest: "{{ wordpress_install_directory }}"
      changed_when: false
      tags: wordpress

    - name: Unzipping wordpress
      unarchive:
        src: "{{ wordpress_install_directory }}/wordpress-{{ wordpress_version }}.tar.gz"
        dest: "{{ wordpress_install_directory }}"
        remote_src: true
        owner: root
        group: apache
        setype: httpd_sys_rw_content_t
        creates: "{{ wordpress_directory }}"
      tags: wordpress

    - name: Remove wordpress.tar.gz file
      file:
        path: "{{ wordpress_install_directory }}/wordpress-{{ wordpress_version }}.tar.gz"
        state: absent
      changed_when: false
      tags: wordpress